import type { Metadata } from "next";
import { Inter } from "next/font/google";

import Sidebar from "@/app/component/Sidebar";
import Header from "@/app/component/Header";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "IMS App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${inter.className}`}>
        <Header/>
        <div className="flex">
        <Sidebar/>
        <main className="mt-20 ml-72">
        {children}
        </main>
        </div>
        </body>
    </html>
  );
}
